apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config
  labels:
    app: projet-final
    tier: back
data:
  DB_HOST: "postgres-db-service"
  DB_PORT: "5432"
  DB_USER: "user"
  DB_NAME: "mydb"
  BACK_PORT: "8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: back-secret
  labels:
    app: projet-final
    tier: back
type: Opaque
data:
  DB_PASSWORD: dzU0RHFIVHJCRjdBVWNBR29PU0ZuTmVCbw==
