apiVersion: v1
kind: Service
metadata:
  name: front-service-nodeport
  labels:
    app: projet-final
    tier: front
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: projet-final
    tier: front

