apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projet-final

resources:
  - ../../k8s/db-secret.yml
  - ../../k8s/back-config-secret.yml
  - ../../k8s/db-pvc.yml
  - ../../k8s/db-deployment.yml
  - ../../k8s/back-deployment.yml
  - ../../k8s/front-deployment.yml
  - ../../k8s/front-ingress.yml
  - ../../k8s/hpa-back.yml
  - ../../k8s/hpa-front.yml

commonLabels:
  app: projet-final
  managed-by: kustomize

