apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projet-final-dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: back-deployment
    count: 1
  - name: front-deployment
    count: 1

patchesStrategicMerge:
  - deployment-patch.yml
  - resources-patch.yml

configMapGenerator:
  - name: back-config
    behavior: merge
    literals:
      - ENV=development
      - DEBUG=true

commonLabels:
  environment: development

